config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :entries
  get 'signup', to: 'users#new'
  resources :users, only: [:new, :create]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
  attr_accessor :date
    scope :this_month, -> { where(created_at: Date.today.all_month) }

    # validates_presence_of :this_month
end

app/models/user.rb
class User < ApplicationRecord
  has_many :entries
  validates :username, presence: true, 
            uniqueness: { case_sensitive: false }, 
            length: { minimum: 3, maximum: 25 }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/entries_controller.rb
require 'date'
require "active_support"
require "active_support/core_ext/date/calculations"

# ActiveRecord::Base.connection.reset_pk_sequence!('Entries')
class EntriesController < ApplicationController
  def index
    @entries = Entry.all.sort_by(&:updated_at)
  end

  def create
    @entry = Entry.new(params.require(:entry).permit(:drinks, :log, :updated_at))
    drinks = params[:entry][:drinks].to_i
    date = params[:entry][:date].to_date
    @entry.updated_at = date
    @entry.drinks = drinks
    @entry.save!
    # binding.break
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if !Entry.last.blank?
      @month_entries = Entry.this_month
    end_of_month = Date.today.at_end_of_month.strftime('%d').to_f
    
    # get number of sober days for month
    @get_month_alc_free_days = @month_entries.select{ |entry|
      entry.drinks == 0
    }.count
    
    @sober_days_in_month = (( @get_month_alc_free_days / end_of_month) * 100).to_i

    # get sober days this year
    @sober_days_of_year = Entry.all.select { |entry|
      entry.drinks == 0
    }.count

    # get number of drinks for the month
    @no_of_drinks = 0
    @drinks_this_month = @month_entries.select{|entry|
      # create variable and add when drinks are added
      if  entry.drinks != 0 then @no_of_drinks += entry.drinks end
    }.count

  else return nil
  end
end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged In Successfully"
      redirect_to new_entry_path
    else
      flash.now[:alert] = "There was something wrong with your login details"
      render 'new'
    end
  end

  def login
  end

  def welcome
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:username, :password))
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "#{@user.username}, You have successfully signed up"
      redirect_to root_path
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entries/index.html.erb
  <h1>Entries</h1>
<div class="graph">
<%= line_chart Entry.group_by_day(:updated_at).maximum(:drinks) %>
</div>
<footer><%= link_to 'Back', root_path %></footer>

app/views/entries/new.html.erb
    <h1>Intake</h1>
     
    <%= form_with scope: :entry, url: entries_path, local: true do |f| %>
      <p> 
        <%= f.label :drinks %><br/> 
        <%= f.number_field :drinks %>
      </p>
      <p>
        <%= f.label :updated_at %><br/> 
        <%= f.date_field :date %> 
      </p>      
      <p>
        <%= f.submit %> 
      </p>
    <% end %>

<%= link_to "Go Back", root_path %>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-success alert-dimissable fade show">
    <%= msg %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlcoholTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>atina's tracker app</h1>

<div>
  <p>Practicing sobriety since: <%= DateTime.new(2022,3,24).strftime("%F") %> </p>
</div>

<div class="stats">
  <div>
    <p>I've been alcohol free for</p>
    <p><strong><%= @get_month_alc_free_days %></strong> days this month</p>
    <p><strong><%= @sober_days_of_year %></strong> days this year</p>
  </div>
  <div>
    <p>I've had</p>
    <p> <strong><%= @no_of_drinks %></strong> drinks this month </p>
    <p><strong><%= @drinks_this_month %></strong> days of drinking </p>
  </div>
</div>

<div class='' style="display: flex; justify-content: space-evenly; align-items: center;">
  <p class="pie animate" style="--p:<%= @sober_days_in_month %>;--c:darkblue;--b:10px"><%= @sober_days_in_month %>% of <%= DateTime.now().strftime('%b')%></p>
  <div class="add_entry_container">
    <%= link_to  logged_in? ? new_entry_path : login_path do %>
      <div class="button">
        <div class="icon">
            <i class="fa fa-solid fa-plus"></i>
        </div>
      </div>
    <% end %>
  </div>
</div>


<div class="graph">
  <%= line_chart Entry.this_month.group_by_day(:updated_at).maximum(:drinks) %>
</div>

<footer><%= link_to 'See All Time Entries', entries_path %></footer>

app/views/shared/errors.html.erb
<% if obj.errors.any? %>

<div class="alert alert-danger alert-dimissable fade show " role="alert">
  <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
  <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
   <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

<% end %>

app/views/users/_form.html.erb
<div class="container">
  
  <div class="row d-flex justify-content-center">
    <div class="col-10">
      <% if @user.errors.any? %>
      <h2>The following errors prevented the user from being saved:</h2>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      <% end %>

      <%= form_with(model: @user, local: true, class:"shadow p-3 mb-3 bg-info rounded") do |f|%>
        <div class="form-group row mt-4">
            <%= f.label :username, class:"col-2 col-form-label text-light" %>
            <div class="col-10">
              <%= f.text_field :username, class:"form-control shadow rounded", placeholder: "Username" %>
            </div>
          </div>

        <div class="form-group row mt-4">
            <%= f.label :password, class:"col-2 col-form-label text-light" %>
            <div class="col-10">
              <%= f.password_field :password, class:"form-control shadow rounded", placeholder: "Password" %>
            </div>
          </div>

      
          <div class="form-group row mt-4">
            <%= f.submit("Sign Up", class:"btn btn-outline-light btn-lg") %>
          </div>
        </div>
      
      <% end %>
    </div>
  
  
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1 class="display-4 text-center mt-4">Make an Account</h1>

<%= render 'form' %>